# Generated by Django 4.0.4 on 2022-11-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0003_remove_user_created_remove_user_signedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnigPathNumber', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('startedAt', models.DateTimeField()),
                ('finishedAt', models.DateTimeField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Take_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_answer')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_question')),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.take')),
            ],
        ),
        migrations.AddField(
            model_name='quiz_answer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_question'),
        ),
    ]
