# Generated by Django 4.0.4 on 2022-11-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0004_quiz_quiz_answer_quiz_question_take_take_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rankPoints',
        ),
    ]
