# Generated by Django 4.0.4 on 2022-11-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0005_remove_user_rankpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(null=True, to='BackednApp.user'),
        ),
    ]
