# Generated by Django 4.0.4 on 2022-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0006_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictyconsumption',
            name='totalconsumption',
            field=models.IntegerField(default=0),
        ),
    ]
