# Generated by Django 4.0.4 on 2022-11-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0008_alter_electrictyconsumption_totalconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrictyconsumption',
            name='totalconsumption',
        ),
        migrations.AddField(
            model_name='electrictyconsumption',
            name='totalusage',
            field=models.IntegerField(null=True),
        ),
    ]
